export interface TelemetryEvent {
    schema_version: string;
    event_id: string;
    interaction_key: string;
    source: 'copilot' | 'codex';
    assistant_client: 'vscode' | 'cursor' | 'codex' | 'unknown';
    assistant_name: string;
    timestamp: string;
    session_id: string;
    workspace_id: string;
    workspace_path: string;
    copilot_version: string;
    vscode_version: string;
    session_producer: string;
    session_schema_version: number;
    interaction_number: number;
    assistant_turns_count: number;
    user_message_event_id: string | null;
    user_message_timestamp: string;
    first_turn_start_timestamp: string | null;
    last_turn_end_timestamp: string;
    prompt_char_length: number;
    estimated_input_tokens: number;
    response_char_length: number;
    estimated_output_tokens: number;
    context_files_count: number;
    attachment_types: string[];
    tool_calls_count: number;
    tool_names: string[];
    tool_breakdown: Record<string, number>;
    tool_success_count: number;
    tool_failure_count: number;
    tool_latency_ms_total: number;
    tool_latency_ms_avg: number;
    tool_argument_char_length_total: number;
    files_read: string[];
    task_type: string;
    latency_ms: number;
    idle_ms_since_prev_interaction: number | null;
    has_reasoning: boolean;
    reasoning_char_length: number;
    reasoning_message_count: number;
}

export interface BuildEventParams {
    interactionKey: string;
    source: 'copilot' | 'codex';
    assistantClient: 'vscode' | 'cursor' | 'codex' | 'unknown';
    assistantName: string;
    workspacePath?: string;
    sessionId: string;
    copilotVersion: string;
    vscodeVersion: string;
    sessionProducer: string;
    sessionSchemaVersion: number;
    interactionNumber: number;
    assistantTurnsCount: number;
    userMessageEventId: string | null;
    userMessageTimestamp: string;
    firstTurnStartTimestamp: string | null;
    lastTurnEndTimestamp: string;
    promptCharLength: number;
    responseCharLength: number;
    contextFilesCount: number;
    attachmentTypes: string[];
    toolCallsCount: number;
    toolNames: string[];
    toolBreakdown: Record<string, number>;
    toolSuccessCount: number;
    toolFailureCount: number;
    toolLatencyMsTotal: number;
    toolLatencyMsAvg: number;
    toolArgumentCharLengthTotal: number;
    filesRead: string[];
    taskType: string;
    latencyMs: number;
    idleMsSincePrevInteraction: number | null;
    hasReasoning: boolean;
    reasoningCharLength: number;
    reasoningMessageCount: number;
    timestamp: string;
}
